# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
      workflow_dispatch:
jobs:
  deploy-test-1:
    runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v2
      - run: npm test
      - uses: acesarfl@everis.nttdata.com/heroku-deploy@master
        with:
          heroku_api_key: "cGjRvecouz8F+G+JySp1roX+JtyiM8wvNLf8cX3h7ZsZT6COKKzJoNMfNMDhplKIQDw1YjAlQBhkGVint5ctazB/d/e/cIy+eHAg2XrqC23TazE+qJ5rHj2iy/mxCkaNR03t2+4nkpl0crGZK7sSqbdJhgsHSGLAHOIpjYDrMcqUPHoKL0wPLRaDZPznGTUoK/OHb1y+OzlbGbmuTqrsd0lq3pPSINKe3exr+2xJTh/tfGRCT5tThTsqAesuq9kyAljxnwuNlCM7mStwRFwPElc7srsA5K978z1MI49FPGjlz6DPU1olX6Ip3ydGI89OD33VdZ4mX3D+8I69S6lknImdR/4E22bgJCPl8etFfEekZIxsby57W0Ykpi9C1bSRIYKtwiqnjbK1/PCg8KeOWEW9Hw148S7pDb38TSbI/+ZT2iAP57CCFjBnBEl6czfgv1Mcoh7TzYre5aJyvMC0rSewWjOa0WwZHs5UDe2oOsG4kbQYcmPBkSF9rTW+VhI0Y4rJiWYsrOfYhW3kRYyk5LXFH2F4kNRp3TMnSnga2xurlDKpufkK5K20exqPYAToYcVwvyy7z/76WMQ9Lqwb4qS74Qs32VGhrVqp5VPT8SmfGp81j4tNo/s7w0LzNOT5YEtgOxWF/pHrfh7KiHB2PRwNiMrokJWHMrQ2IFQMRr8="
          heroku_app_name: "tony-devops"
          heroku_email: "acesarfl@everis.nttdata.com"
         
  deploy-test-2:
    runs-on: ubuntu-latest
    needs: deploy-test-1
    steps:
      - uses: actions/checkout@v2
      - run: npm test
      - uses: akhileshns/heroku-deploy@master
        with:
          heroku_api_key: "cGjRvecouz8F+G+JySp1roX+JtyiM8wvNLf8cX3h7ZsZT6COKKzJoNMfNMDhplKIQDw1YjAlQBhkGVint5ctazB/d/e/cIy+eHAg2XrqC23TazE+qJ5rHj2iy/mxCkaNR03t2+4nkpl0crGZK7sSqbdJhgsHSGLAHOIpjYDrMcqUPHoKL0wPLRaDZPznGTUoK/OHb1y+OzlbGbmuTqrsd0lq3pPSINKe3exr+2xJTh/tfGRCT5tThTsqAesuq9kyAljxnwuNlCM7mStwRFwPElc7srsA5K978z1MI49FPGjlz6DPU1olX6Ip3ydGI89OD33VdZ4mX3D+8I69S6lknImdR/4E22bgJCPl8etFfEekZIxsby57W0Ykpi9C1bSRIYKtwiqnjbK1/PCg8KeOWEW9Hw148S7pDb38TSbI/+ZT2iAP57CCFjBnBEl6czfgv1Mcoh7TzYre5aJyvMC0rSewWjOa0WwZHs5UDe2oOsG4kbQYcmPBkSF9rTW+VhI0Y4rJiWYsrOfYhW3kRYyk5LXFH2F4kNRp3TMnSnga2xurlDKpufkK5K20exqPYAToYcVwvyy7z/76WMQ9Lqwb4qS74Qs32VGhrVqp5VPT8SmfGp81j4tNo/s7w0LzNOT5YEtgOxWF/pHrfh7KiHB2PRwNiMrokJWHMrQ2IFQMRr8="
          heroku_app_name: "tony-devops"
          heroku_email: "acesarfl@everis.nttdata.com"
          #appdir: "tests/test-4"
          healthcheck: "https://tony-devops.herokuapp.com/"
          checkstring: "ok"
          procfile: "web: gunicorn index:app"
      - run: npm run test-action https://tony-devops.herokuapp.com/
