name: "Deploy to Heroku"
description: "Deploy an app to Heroku"
branding:
  icon: "upload-cloud"
  color: "purple"
inputs:
  heroku_api_key:
    description: "18a1bf8d-02c4-4455-aa82-b810446c65f2"
    required: true
  heroku_email:
    description: "acesarfl@everis.nttdata.com"
    required: true
  heroku_app_name:
    description: "tony-devops"
    required: true
  buildpack:
    description: "An optional buildpack to use when creating the heroku application"
    required: false
  branch:
    description: "main"
    default: "HEAD"
    required: false
  dontuseforce:
    description: "false"
    default: "false"
    required: false
  dontautocreate:
    description: "Set this to true if you don't want to automatically create the Heroku app"
    default: "false"
    required: false
  usedocker:
    description: "Will deploy using Dockerfile in project root."
    default: "false"
    required: false
  docker_heroku_process_type:
    description: "Type of heroku process (web, worker, etc). This option only makes sense when usedocker enabled"
    default: "web"
    required: false
  docker_build_args:
    description: "A list of args to pass into the Docker build. This option only makes sense when usedocker enabled"
    required: false
  appdir:
    description: "Set if your app is located in a subdirectory."
    default: ""
    required: false
  healthcheck:
    description: "A URL to which a healthcheck is performed (checks for 200 request)"
    required: false
    default: ""
  checkstring:
    description: "Value to check for when conducting healthcheck request"
    required: false
    default: ""
  delay:
    description: "Time (in seconds) to wait before performing healthcheck"
    required: false
    default: "0"
outputs:
  status:
    description: "The Success/Failure of the action"
runs:
  using: "node12"
  main: "index.js"